### ISSUE TITLE
Namespaces problem

### ISSUE THREAD

**Issue by excitoon** [kevinboone/epub2txt#7]
Sometimes epub files contain nodes with namespaces in metadata:
```
 10   <opf:manifest>
 11     <opf:item href="toc.ncx" id="ncx" media-type="application/x-dtbncx+xml"/>
 12     <opf:item href="html/styles/9781471147258.css" id="css1" media-type="text/css"/>
 13     <opf:item href="html/styles/nomargin.css" id="css2" media-type="text/css"/>
 14     <opf:item href="html/fonts/FreeSerif.ttf" id="font1" media-type="application/x-truetype-font"/>
```
epub2txt can't find a manifest in this case. I attach sample file which doesn't work. [GoodbyeVitamin.epub.zip](https://github.com/kevinboone/epub2txt/files/1308297/GoodbyeVitamin.epub.zip)

I worked around this bug for me in this commit: https://github.com/excitoon/epub2txt/commit/5738b58c2c7d8d255ef14ae210bb795b915bd2a2 .

**Comment by rhn-support-kboone** [comment]
Thanks. I will include a fix based on your suggestion in the next commit. Because we have no idea, in principle, what the XML namespace will be, I think the code should check for ":manifest" at any position, rather than specifically "opf:manifest," as you suggested. The EPUB sample you uploaded is well-formed, and it's nobody's fault except mine that epub2txt uses such a crude XML parser. This is the first EPUB I've seen that actually uses XML namespaces in this way.
